fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  registration:
    confirmation:
      enabled: false
  from_email:
    address: "test@domain.com"
    sender_name: "test@domain.com"
  service:
    user_manager: sonata.user.orm.user_manager
    mailer: 'fos_user.mailer.noop'
  group:
    group_class:   App\Entity\Group
    group_manager: sonata.user.orm.group_manager
